# Generated by Django 5.2 on 2025-07-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarySentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('original_sentence', models.TextField()),
                ('corrected_sentence', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diary_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
