# Generated by Django 5.2 on 2025-07-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectUI', '0002_diary_remove_diarysentence_diary_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='summary',
            new_name='entire_diary',
        ),
    ]
